export const catalogInfo = {
  "checked": "2026-09-27",
  "elLoboPublicVideos": 62,
  "woodburySelections": 4,
  "elLoboPaginationComplete": true,
  "woodburyPending": [
    "Mr. Jones retirement",
    "Justin Timberlake",
    "Woodbury yearbook archive"
  ],
  "releaseMetadata": "Matched Apple Music/iTunes track listings; unresolved releases remain explicitly unconfirmed."
};
export const videos = [
  {
    "id": "wAELib0i6pc",
    "title": "Arctic Monkeys-Temptation Greets You Like Your Naughty Friend (Drum Reproduction)",
    "song": "Temptation Greets You Like Your Naughty Friend",
    "artist": "Arctic Monkeys",
    "collection": "covers",
    "performance": "Drum cover",
    "release": "Brianstorm - Single",
    "releaseSource": "https://music.apple.com/us/album/temptation-greets-you-like-your-naughty-friend/251054049?i=251054310&uo=4",
    "genre": "Alternative",
    "duration": 210,
    "date": "2016-05-10",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=wAELib0i6pc"
  },
  {
    "id": "3joCpMucsgg",
    "title": "Arctic Monkeys-Leave Before The Lights Come On (Drum Cover)",
    "song": "Leave Before The Lights Come On",
    "artist": "Arctic Monkeys",
    "collection": "covers",
    "performance": "Drum cover",
    "release": "Leave Before the Lights Come On - EP",
    "releaseSource": "https://music.apple.com/us/album/leave-before-the-lights-come-on/178359939?i=178359944&uo=4",
    "genre": "Alternative",
    "duration": 231,
    "date": "2016-05-09",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=3joCpMucsgg"
  },
  {
    "id": "n5YdGyoMgok",
    "title": "Arctic Monkeys-Balaclava (Drum)",
    "song": "Balaclava",
    "artist": "Arctic Monkeys",
    "collection": "covers",
    "performance": "Drum cover",
    "release": "Favourite Worst Nightmare",
    "releaseSource": "https://music.apple.com/us/album/balaclava/251499221?i=251499387&uo=4",
    "genre": "Alternative",
    "duration": 176,
    "date": "2016-01-21",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=n5YdGyoMgok"
  },
  {
    "id": "mMa2XGCcSaE",
    "title": "Arctic Monkeys - View from the Afternoon (drum cover)",
    "song": "View from the Afternoon",
    "artist": "Arctic Monkeys",
    "collection": "covers",
    "performance": "Drum cover",
    "release": "Whatever People Say I Am, That's What I'm Not",
    "releaseSource": "https://music.apple.com/us/album/the-view-from-the-afternoon/111153953?i=111153346&uo=4",
    "genre": "Alternative",
    "duration": 235,
    "date": "2015-10-03",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=mMa2XGCcSaE"
  },
  {
    "id": "GsHSHD_UPBY",
    "title": "Stevie Wonder-Ribbon in the Sky cover",
    "song": "Ribbon in the Sky",
    "artist": "Stevie Wonder",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Original Musiquarium",
    "releaseSource": "https://music.apple.com/us/album/ribbon-in-the-sky-1982-musiquarium-version/1440757544?i=1440757565&uo=4",
    "genre": "R&B/Soul",
    "duration": 66,
    "date": "2013-01-16",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=GsHSHD_UPBY"
  },
  {
    "id": "t-7kiwuzXPw",
    "title": "Chim Chim Cher-ee",
    "song": "Chim Chim Cher-ee",
    "artist": "Standards & soundtracks",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Mary Poppins (Original Motion Picture Soundtrack)",
    "releaseSource": "https://music.apple.com/us/album/chim-chim-cher-ee/1440796512?i=1440796680&uo=4",
    "genre": "Musicals",
    "duration": 80,
    "date": "2012-10-25",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=t-7kiwuzXPw"
  },
  {
    "id": "bKPvgHamBiE",
    "title": "Bei Mir Bist du Schon cover",
    "song": "Bei Mir Bist du Schon",
    "artist": "Standards & soundtracks",
    "collection": "covers",
    "performance": "Cover performance",
    "release": null,
    "releaseSource": null,
    "genre": null,
    "duration": 151,
    "date": "2012-08-06",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=bKPvgHamBiE"
  },
  {
    "id": "iWt-CJsJyUw",
    "title": "Bobby Hebb-Sunny (Cover)",
    "song": "Sunny",
    "artist": "Bobby Hebb",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Sunny",
    "releaseSource": "https://music.apple.com/us/album/sunny/1440918582?i=1440918584&uo=4",
    "genre": "Pop",
    "duration": 153,
    "date": "2012-07-21",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=iWt-CJsJyUw"
  },
  {
    "id": "BYOar_8NCoY",
    "title": "Sly & The Family Stone-If You Want Me To Stay (cover)",
    "song": "If You Want Me To Stay",
    "artist": "Sly & The Family Stone",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Fresh",
    "releaseSource": "https://music.apple.com/us/album/if-you-want-me-to-stay/216546627?i=216546781&uo=4",
    "genre": "R&B/Soul",
    "duration": 190,
    "date": "2012-05-15",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=BYOar_8NCoY"
  },
  {
    "id": "0NQs01Fxp0w",
    "title": "Boney M - Rapsutin Drum Cover",
    "song": "Rasputin",
    "artist": "Boney M",
    "collection": "covers",
    "performance": "Drum cover",
    "release": "Nightflight to Venus (2007 Remastered Version)",
    "releaseSource": "https://music.apple.com/us/album/rasputin-2007-remastered-version/250727571?i=250727626&uo=4",
    "genre": "R&B/Soul",
    "duration": 320,
    "date": "2012-01-31",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=0NQs01Fxp0w"
  },
  {
    "id": "vFsyHJkmfcU",
    "title": "Alex Turner-Stuck on the Puzzle Cover",
    "song": "Stuck on the Puzzle",
    "artist": "Alex Turner",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Submarine - EP",
    "releaseSource": "https://music.apple.com/us/album/stuck-on-the-puzzle/422325910?i=422326077&uo=4",
    "genre": "Alternative",
    "duration": 52,
    "date": "2011-12-20",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=vFsyHJkmfcU"
  },
  {
    "id": "B8-7LOTimC8",
    "title": "Paul McCartney Wings - Bip Bop Link Cover",
    "song": "Bip Bop Link",
    "artist": "Paul McCartney & Wings",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Wild Life (2018 Remaster)",
    "releaseSource": "https://music.apple.com/us/album/bip-bop-link/1446532408?i=1446532419&uo=4",
    "genre": "Rock",
    "duration": 52,
    "date": "2011-11-02",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=B8-7LOTimC8"
  },
  {
    "id": "QAwAh0Fhnu4",
    "title": "Portugal. The Man - Head Is a Flame (Cool With It) Cover",
    "song": "Head Is a Flame (Cool With It)",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "In the Mountain In the Cloud",
    "releaseSource": "https://music.apple.com/us/album/head-is-a-flame-cool-with-it/439947544?i=439947616&uo=4",
    "genre": "Alternative",
    "duration": 248,
    "date": "2011-10-07",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=QAwAh0Fhnu4"
  },
  {
    "id": "h_tQCbuGzyg",
    "title": "The Yardbirds-I'm Not Talking cover",
    "song": "I'm Not Talking",
    "artist": "The Yardbirds",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "The Yardbirds Story",
    "releaseSource": "https://music.apple.com/us/album/im-not-talking/659693808?i=659695131&uo=4",
    "genre": "Rock",
    "duration": 171,
    "date": "2011-09-10",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=h_tQCbuGzyg"
  },
  {
    "id": "vE1dNisI3Wo",
    "title": "Portugal. The Man-Once Was One cover",
    "song": "Once Was One",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "In the Mountain In the Cloud",
    "releaseSource": "https://music.apple.com/us/album/once-was-one/439947544?i=439947637&uo=4",
    "genre": "Alternative",
    "duration": 262,
    "date": "2011-08-06",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=vE1dNisI3Wo"
  },
  {
    "id": "zV8Hr49CR3k",
    "title": "Portugal. The Man-Share With Me The Sun",
    "song": "Share With Me The Sun",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "In the Mountain In the Cloud",
    "releaseSource": "https://music.apple.com/us/album/share-with-me-the-sun/439947544?i=439947640&uo=4",
    "genre": "Alternative",
    "duration": 170,
    "date": "2011-07-25",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=zV8Hr49CR3k"
  },
  {
    "id": "hzWaQ_q31aw",
    "title": "Portugal. The Man-Chicago cover",
    "song": "Chicago",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Waiter: \"You Vultures!\"",
    "releaseSource": "https://music.apple.com/us/album/chicago/1442222711?i=1442223556&uo=4",
    "genre": "Alternative",
    "duration": 282,
    "date": "2011-07-14",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=hzWaQ_q31aw"
  },
  {
    "id": "LBBYOOvfrdw",
    "title": "The Yardbirds-Chris' Number",
    "song": "Chris' Number",
    "artist": "The Yardbirds",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "The Yardbirds Story",
    "releaseSource": "https://music.apple.com/us/album/chris-number/659693808?i=659696665&uo=4",
    "genre": "Rock",
    "duration": 147,
    "date": "2011-07-03",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=LBBYOOvfrdw"
  },
  {
    "id": "-dSRozuqZ6g",
    "title": "Portugal. The Man-Sleep Forever Cover",
    "song": "Sleep Forever",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "In the Mountain In the Cloud",
    "releaseSource": "https://music.apple.com/us/album/sleep-forever/439947544?i=439947643&uo=4",
    "genre": "Alternative",
    "duration": 309,
    "date": "2011-07-03",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=-dSRozuqZ6g"
  },
  {
    "id": "ry013sE91T8",
    "title": "The New Vaudeville Band - Winchester Cathedral cover",
    "song": "Winchester Cathedral",
    "artist": "The New Vaudeville Band",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "British Invasion Greatest Hits",
    "releaseSource": "https://music.apple.com/us/album/winchester-cathedral/1571518448?i=1571518762&uo=4",
    "genre": "Britpop",
    "duration": 151,
    "date": "2011-06-22",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=ry013sE91T8"
  },
  {
    "id": "WGaku9ZORdc",
    "title": "Portugal. The Man - The Pines",
    "song": "The Pines",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Devil Say I, I Say Air - EP",
    "releaseSource": "https://music.apple.com/us/album/the-pines/1445157289?i=1445157292&uo=4",
    "genre": "Alternative",
    "duration": 227,
    "date": "2011-05-28",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=WGaku9ZORdc"
  },
  {
    "id": "SAH4tmjUJZs",
    "title": "Portugal. The Man-Waiter",
    "song": "Waiter",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Waiter: \"You Vultures!\"",
    "releaseSource": "https://music.apple.com/us/album/waiter/1442222711?i=1442223450&uo=4",
    "genre": "Alternative",
    "duration": 233,
    "date": "2011-04-25",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=SAH4tmjUJZs"
  },
  {
    "id": "bD3TulxcyJQ",
    "title": "Stevie Wonder-Sir Duke cover",
    "song": "Sir Duke",
    "artist": "Stevie Wonder",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Songs in the Key of Life",
    "releaseSource": "https://music.apple.com/us/album/sir-duke/1440788438?i=1440788542&uo=4",
    "genre": "R&B/Soul",
    "duration": 174,
    "date": "2011-04-14",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=bD3TulxcyJQ"
  },
  {
    "id": "hatxhWldG_A",
    "title": "The Ventures-Walk Don't Run Cover",
    "song": "Walk Don't Run",
    "artist": "The Ventures",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Walk Don't Run",
    "releaseSource": "https://music.apple.com/us/album/walk-dont-run/1443065914?i=1443066594&uo=4",
    "genre": "Rock",
    "duration": 129,
    "date": "2010-10-12",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=hatxhWldG_A"
  },
  {
    "id": "0XvMVQrIURQ",
    "title": "The Beatles-Girl cover",
    "song": "Girl",
    "artist": "The Beatles",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Rubber Soul",
    "releaseSource": "https://music.apple.com/us/album/girl/1441164359?i=1441164634&uo=4",
    "genre": "Rock",
    "duration": 171,
    "date": "2010-09-06",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=0XvMVQrIURQ"
  },
  {
    "id": "e2cEIo2lKRs",
    "title": "Stevie Wonder-Which Way The Wind",
    "song": "Which Way The Wind",
    "artist": "Stevie Wonder",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Eivets Rednow",
    "releaseSource": "https://music.apple.com/us/album/which-way-the-wind/1444040074?i=1444040424&uo=4",
    "genre": "R&B/Soul",
    "duration": 176,
    "date": "2010-09-06",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=e2cEIo2lKRs"
  },
  {
    "id": "cjBS18zpWjk",
    "title": "Portugal. The Man - Gold Magic Cover",
    "song": "Gold Magic",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "It's Complicated Being a Wizard",
    "releaseSource": "https://music.apple.com/us/album/gold-magic/1537511216?i=1537511626&uo=4",
    "genre": "Alternative",
    "duration": 159,
    "date": "2010-05-03",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=cjBS18zpWjk"
  },
  {
    "id": "eq3EemJIMSI",
    "title": "Portugal. The Man - My Mind Cover",
    "song": "My Mind",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Church Mouth",
    "releaseSource": "https://music.apple.com/us/album/my-mind/1443592747?i=1443593384&uo=4",
    "genre": "Alternative",
    "duration": 250,
    "date": "2010-05-01",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=eq3EemJIMSI"
  },
  {
    "id": "iLHoYyfhxoA",
    "title": "Kay Kay and His Weathered Underground-Oh Lord, I Hate You California",
    "song": "Oh Lord, I Hate You California",
    "artist": "Kay Kay and His Weathered Underground",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Introducing Kay Kay and His Weathered Underground",
    "releaseSource": "https://music.apple.com/us/album/oh-lord-i-hate-you-california/419150646?i=419150678&uo=4",
    "genre": "Alternative",
    "duration": 249,
    "date": "2010-04-15",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=iLHoYyfhxoA"
  },
  {
    "id": "4E_3pAnD8bs",
    "title": "Arctic Monkeys - Riot Van Cover",
    "song": "Riot Van",
    "artist": "Arctic Monkeys",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Whatever People Say I Am, That's What I'm Not",
    "releaseSource": "https://music.apple.com/us/album/riot-van/111153953?i=111153559&uo=4",
    "genre": "Alternative",
    "duration": 154,
    "date": "2010-04-10",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=4E_3pAnD8bs"
  },
  {
    "id": "XKyQhI3Wx6s",
    "title": "The Mamas and The Papas-Words of Love cover",
    "song": "Words of Love",
    "artist": "The Mamas and The Papas",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "The Mamas & the Papas",
    "releaseSource": "https://music.apple.com/us/album/words-of-love-single-version/1423333392?i=1423333811&uo=4",
    "genre": "Pop",
    "duration": 153,
    "date": "2010-03-21",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=XKyQhI3Wx6s"
  },
  {
    "id": "Tmbey9ImMdg",
    "title": "Arctic Monkeys-Too Much To Ask cover",
    "song": "Too Much To Ask",
    "artist": "Arctic Monkeys",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Fluorescent Adolescent - EP",
    "releaseSource": "https://music.apple.com/us/album/too-much-to-ask/262507666?i=262507938&uo=4",
    "genre": "Alternative",
    "duration": 223,
    "date": "2010-03-20",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=Tmbey9ImMdg"
  },
  {
    "id": "f4qv_04-a-Y",
    "title": "Sam Spence-Life on the Wildside",
    "song": "Life on the Wildside",
    "artist": "Sam Spence",
    "collection": "covers",
    "performance": "Cover performance",
    "release": null,
    "releaseSource": null,
    "genre": null,
    "duration": 157,
    "date": "2010-03-13",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=f4qv_04-a-Y"
  },
  {
    "id": "ZLU1SsWfieY",
    "title": "Portugal. The Man-1000 Years",
    "song": "1000 Years",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "American Ghetto",
    "releaseSource": "https://music.apple.com/us/album/1000-years/1537511660?i=1537511667&uo=4",
    "genre": "Alternative",
    "duration": 212,
    "date": "2010-03-08",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=ZLU1SsWfieY"
  },
  {
    "id": "21EZQq5RdHw",
    "title": "John Mayer-Daughters Cover",
    "song": "Daughters",
    "artist": "John Mayer",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Heavier Things",
    "releaseSource": "https://music.apple.com/us/album/daughters/199049977?i=199051362&uo=4",
    "genre": "Rock",
    "duration": 259,
    "date": "2010-02-28",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=21EZQq5RdHw"
  },
  {
    "id": "icoRMFpgCSE",
    "title": "Burt Bacharach-I Say a Little Prayer cover",
    "song": "I Say a Little Prayer",
    "artist": "Burt Bacharach",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Reach Out",
    "releaseSource": "https://music.apple.com/us/album/i-say-a-little-prayer/1444031258?i=1444032038&uo=4",
    "genre": "Pop",
    "duration": 178,
    "date": "2010-02-21",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=icoRMFpgCSE"
  },
  {
    "id": "6bHJVbtkd2Q",
    "title": "Grizzly Bear-While You Wait For The Others cover",
    "song": "While You Wait For The Others",
    "artist": "Grizzly Bear",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Veckatimest (Bonus Tracks)",
    "releaseSource": "https://music.apple.com/us/album/while-you-wait-for-the-others-bbc-maida-vale-session/336895732?i=336895958&uo=4",
    "genre": "Alternative",
    "duration": 298,
    "date": "2010-02-17",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=6bHJVbtkd2Q"
  },
  {
    "id": "d9kPn2yNGTc",
    "title": "Kay Kay and His Weathered Underground-One Ought To See",
    "song": "One Ought To See",
    "artist": "Kay Kay and His Weathered Underground",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Kay Kay and His Weathered Underground",
    "releaseSource": "https://music.apple.com/us/album/one-ought-to-see/277998016?i=277998140&uo=4",
    "genre": "Pop",
    "duration": 225,
    "date": "2010-02-17",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=d9kPn2yNGTc"
  },
  {
    "id": "tBYlZgmqD1E",
    "title": "The Beach Boys-In My Room Cover",
    "song": "In My Room",
    "artist": "The Beach Boys",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Surfer Girl",
    "releaseSource": "https://music.apple.com/us/album/in-my-room/1442921264?i=1442921414&uo=4",
    "genre": "Rock",
    "duration": 143,
    "date": "2010-02-12",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=tBYlZgmqD1E"
  },
  {
    "id": "TjToLJ1lAiU",
    "title": "The Last Shadow Puppets-Meeting Place cover",
    "song": "Meeting Place",
    "artist": "The Last Shadow Puppets",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "The Age of the Understatement",
    "releaseSource": "https://music.apple.com/us/album/the-meeting-place/278689654?i=278689768&uo=4",
    "genre": "Alternative",
    "duration": 235,
    "date": "2010-01-26",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=TjToLJ1lAiU"
  },
  {
    "id": "uakDJ4-YapA",
    "title": "kay kay and his weathered underground-hey momma cover",
    "song": "hey momma",
    "artist": "Kay Kay and His Weathered Underground",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Kay Kay and His Weathered Underground",
    "releaseSource": "https://music.apple.com/us/album/hey-momma/277998016?i=277998025&uo=4",
    "genre": "Pop",
    "duration": 271,
    "date": "2010-01-19",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=uakDJ4-YapA"
  },
  {
    "id": "DcXuNjlsOnE",
    "title": "Portugal. The Man-Created Cover",
    "song": "Created",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Censored Colors",
    "releaseSource": "https://music.apple.com/us/album/created/1537511514?i=1537511709&uo=4",
    "genre": "Alternative",
    "duration": 271,
    "date": "2009-11-20",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=DcXuNjlsOnE"
  },
  {
    "id": "ya3PzbUKzPE",
    "title": "Arctic Monkeys- Cornerstone Cover",
    "song": "Cornerstone",
    "artist": "Arctic Monkeys",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Humbug",
    "releaseSource": "https://music.apple.com/us/album/cornerstone/330283015?i=330283361&uo=4",
    "genre": "Alternative",
    "duration": 233,
    "date": "2009-11-16",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=ya3PzbUKzPE"
  },
  {
    "id": "vSZbVyhFnvk",
    "title": "Arctic Monkeys-The Fire & The Thud Cover",
    "song": "The Fire & The Thud",
    "artist": "Arctic Monkeys",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Humbug",
    "releaseSource": "https://music.apple.com/us/album/fire-and-the-thud/330283015?i=330283329&uo=4",
    "genre": "Alternative",
    "duration": 200,
    "date": "2009-11-14",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=vSZbVyhFnvk"
  },
  {
    "id": "Vs_FqJpEky0",
    "title": "Portugal. The Man-Horse Warming Party",
    "song": "Horse Warming Party",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Waiter: \"You Vultures!\"",
    "releaseSource": "https://music.apple.com/us/album/horse-warming-party/1442222711?i=1442223752&uo=4",
    "genre": "Alternative",
    "duration": 241,
    "date": "2009-11-12",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=Vs_FqJpEky0"
  },
  {
    "id": "FSrVnO_74c8",
    "title": "Portugal. The Man - Marching With 6",
    "song": "Marching With 6",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Waiter: \"You Vultures!\"",
    "releaseSource": "https://music.apple.com/us/album/marching-with-6/1442222711?i=1442223327&uo=4",
    "genre": "Alternative",
    "duration": 203,
    "date": "2009-11-09",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=FSrVnO_74c8"
  },
  {
    "id": "4nZm0ouoq8Y",
    "title": "The Beatles-Michelle",
    "song": "Michelle",
    "artist": "The Beatles",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Rubber Soul",
    "releaseSource": "https://music.apple.com/us/album/michelle/1441164359?i=1441164629&uo=4",
    "genre": "Rock",
    "duration": 238,
    "date": "2009-10-17",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=4nZm0ouoq8Y"
  },
  {
    "id": "UMnOFHt4Eac",
    "title": "Portugal. The Man-The Woods cover",
    "song": "The Woods",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "The Majestic Majesty",
    "releaseSource": "https://music.apple.com/us/album/the-woods-acoustic/1537511235?i=1537511442&uo=4",
    "genre": "Alternative",
    "duration": 231,
    "date": "2009-10-17",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=UMnOFHt4Eac"
  },
  {
    "id": "71MDRs-3e7E",
    "title": "Portugal. The Man-Lovers In Love",
    "song": "Lovers In Love",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "The Satanic Satanist",
    "releaseSource": "https://music.apple.com/us/album/lovers-in-love/1537511193?i=1537511505&uo=4",
    "genre": "Alternative",
    "duration": 227,
    "date": "2009-07-29",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=71MDRs-3e7E"
  },
  {
    "id": "0PhDY_NTLug",
    "title": "Garbage-Cherry Lips (Go Baby Go) cover",
    "song": "Cherry Lips (Go Baby Go)",
    "artist": "Garbage",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Beautiful Garbage",
    "releaseSource": "https://music.apple.com/us/album/cherry-lips-go-baby-go/1442994320?i=1442994334&uo=4",
    "genre": "Rock",
    "duration": 209,
    "date": "2009-07-11",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=0PhDY_NTLug"
  },
  {
    "id": "iMta9k9y1KQ",
    "title": "Portugal. The Man-Sun Brother",
    "song": "Sun Brother",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Church Mouth",
    "releaseSource": "https://music.apple.com/us/album/sun-brother-excerpt/1443592747?i=1443593632&uo=4",
    "genre": "Alternative",
    "duration": 105,
    "date": "2009-06-24",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=iMta9k9y1KQ"
  },
  {
    "id": "iFidw52_eHY",
    "title": "The Watusi",
    "song": "The Watusi",
    "artist": "Standards & soundtracks",
    "collection": "covers",
    "performance": "Cover performance",
    "release": null,
    "releaseSource": null,
    "genre": null,
    "duration": 19,
    "date": "2009-06-23",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=iFidw52_eHY"
  },
  {
    "id": "mJ3aEUHJHO8",
    "title": "Arctic Monkeys-Leave Before The Lights Come On",
    "song": "Leave Before The Lights Come On",
    "artist": "Arctic Monkeys",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Leave Before the Lights Come On - EP",
    "releaseSource": "https://music.apple.com/us/album/leave-before-the-lights-come-on/178359939?i=178359944&uo=4",
    "genre": "Alternative",
    "duration": 292,
    "date": "2009-06-23",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=mJ3aEUHJHO8"
  },
  {
    "id": "rVYYUTv9JzI",
    "title": "The Monkees-Alvin",
    "song": "Alvin",
    "artist": "The Monkees",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "The Birds, The Bees & The Monkees",
    "releaseSource": "https://music.apple.com/us/album/alvin/23419749?i=23419828&uo=4",
    "genre": "Pop",
    "duration": 28,
    "date": "2009-06-06",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=rVYYUTv9JzI"
  },
  {
    "id": "-09aFXsV-RI",
    "title": "Portugal. The Man-People Say",
    "song": "People Say",
    "artist": "Portugal. The Man",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "The Satanic Satanist",
    "releaseSource": "https://music.apple.com/us/album/people-say/1537511193?i=1537511501&uo=4",
    "genre": "Alternative",
    "duration": 250,
    "date": "2009-06-05",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=-09aFXsV-RI"
  },
  {
    "id": "j0MtAxLfrtw",
    "title": "Portugal. the Man-People Say",
    "song": "People Say",
    "artist": "Portugal. The Man",
    "collection": "archive",
    "performance": "Archived TV performance",
    "release": "The Satanic Satanist",
    "releaseSource": "https://music.apple.com/us/album/people-say/1537511193?i=1537511501&uo=4",
    "genre": "Alternative",
    "duration": 191,
    "date": "2009-04-23",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=j0MtAxLfrtw"
  },
  {
    "id": "v6bSqDW6qmI",
    "title": "Arctic Monkeys-Balaclava cover",
    "song": "Balaclava",
    "artist": "Arctic Monkeys",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Favourite Worst Nightmare",
    "releaseSource": "https://music.apple.com/us/album/balaclava/251499221?i=251499387&uo=4",
    "genre": "Alternative",
    "duration": 221,
    "date": "2009-04-22",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=v6bSqDW6qmI"
  },
  {
    "id": "93nt8UgXGgU",
    "title": "Portugal. The Man-People Say",
    "song": "People Say",
    "artist": "Portugal. The Man",
    "collection": "archive",
    "performance": "Archived TV performance",
    "release": "The Satanic Satanist",
    "releaseSource": "https://music.apple.com/us/album/people-say/1537511193?i=1537511501&uo=4",
    "genre": "Alternative",
    "duration": 188,
    "date": "2009-04-22",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=93nt8UgXGgU"
  },
  {
    "id": "DhPrYXEBRUQ",
    "title": "Arctic Monkeys- Pretty Visitors",
    "song": "Pretty Visitors",
    "artist": "Arctic Monkeys",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "Humbug",
    "releaseSource": "https://music.apple.com/us/album/pretty-visitors/330283015?i=330283382&uo=4",
    "genre": "Alternative",
    "duration": 146,
    "date": "2009-01-31",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=DhPrYXEBRUQ"
  },
  {
    "id": "A1SD6j_HRMo",
    "title": "The Last Shadow Puppets- Gas Dance (drum cover)",
    "song": "Gas Dance",
    "artist": "The Last Shadow Puppets",
    "collection": "covers",
    "performance": "Drum cover",
    "release": "Standing Next to Me - EP",
    "releaseSource": "https://music.apple.com/us/album/gas-dance/284483061?i=284483099&uo=4",
    "genre": "Alternative",
    "duration": 241,
    "date": "2008-11-25",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=A1SD6j_HRMo"
  },
  {
    "id": "K4prIObhVp0",
    "title": "Gerry and the Pacemakers-It's gonna be Alright cover",
    "song": "It's gonna be Alright",
    "artist": "Gerry and the Pacemakers",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "A's B's & EP's",
    "releaseSource": "https://music.apple.com/us/album/its-gonna-be-alright/697072232?i=697072831&uo=4",
    "genre": "Rock",
    "duration": 174,
    "date": "2008-10-21",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=K4prIObhVp0"
  },
  {
    "id": "f3V3sieqyzQ",
    "title": "the last shadow puppets- calm like you (cover)",
    "song": "calm like you",
    "artist": "The Last Shadow Puppets",
    "collection": "covers",
    "performance": "Cover performance",
    "release": "The Age of the Understatement",
    "releaseSource": "https://music.apple.com/us/album/calm-like-you/278689654?i=278689719&uo=4",
    "genre": "Alternative",
    "duration": 133,
    "date": "2008-05-15",
    "channel": "EL LOBO",
    "channelUrl": "https://www.youtube.com/@diddypopdiddy",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=f3V3sieqyzQ"
  },
  {
    "id": "to_zBCm_o8g",
    "title": "My Lesson Plan - God’s Plan (School Edition)",
    "song": "My Lesson Plan",
    "artist": "Woodbury",
    "collection": "woodbury",
    "performance": "School music video",
    "release": null,
    "releaseSource": null,
    "genre": null,
    "duration": 301,
    "date": "2018-04-12",
    "channel": "Woodbury Herd Video Archive",
    "channelUrl": "https://www.youtube.com/@HERDvideoarchive",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=to_zBCm_o8g"
  },
  {
    "id": "DprNcY86Coo",
    "title": "Drake - Fake Love (Parody Video/School Edition)",
    "song": "Fake Love",
    "artist": "Woodbury",
    "collection": "woodbury",
    "performance": "School music video",
    "release": null,
    "releaseSource": null,
    "genre": null,
    "duration": 271,
    "date": "2017-02-09",
    "channel": "Woodbury Herd Video Archive",
    "channelUrl": "https://www.youtube.com/@HERDvideoarchive",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=DprNcY86Coo"
  },
  {
    "id": "V41fqY6B2Bs",
    "title": "MRS. DUNHAM - HAPPY (RETIREMENT)",
    "song": "Mrs. Dunham — Happy (Retirement)",
    "artist": "Woodbury",
    "collection": "woodbury",
    "performance": "School music video",
    "release": null,
    "releaseSource": null,
    "genre": null,
    "duration": 490,
    "date": "2014-06-04",
    "channel": "Woodbury Herd Video Archive",
    "channelUrl": "https://www.youtube.com/@HERDvideoarchive",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=V41fqY6B2Bs"
  },
  {
    "id": "BWTXYswihYU",
    "title": "Woodbury Elementary Schools-THE S.L.A.G. SONG",
    "song": "The S.L.A.G. Song",
    "artist": "Woodbury",
    "collection": "woodbury",
    "performance": "School music video",
    "release": null,
    "releaseSource": null,
    "genre": null,
    "duration": 244,
    "date": "2014-05-14",
    "channel": "Woodbury Herd Video Archive",
    "channelUrl": "https://www.youtube.com/@HERDvideoarchive",
    "embeddable": true,
    "sourceUrl": "https://www.youtube.com/watch?v=BWTXYswihYU"
  }
];
