import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {canStand,moveBody,findPath,clearLine,worldMovement,roomAt} from './navigation.mjs';
const world=JSON.parse(fs.readFileSync(new URL('./room-manifest.json',import.meta.url)));
test('every room is reachable through real doorways, in both directions',()=>{for(const a of world.rooms)for(const b of world.rooms){const path=findPath(a.waypoint,b.waypoint,world);assert.ok(path?.length,`${a.id} to ${b.id}`);let previous=a.waypoint;for(const p of path){assert.ok(clearLine(previous,p,world),`${a.id} to ${b.id}: segment through wall`);previous=p;}assert.equal(roomAt(previous[0],previous[2],world)?.id,b.id);}});
test('walking cannot tunnel through a wall, including large frame deltas',()=>{const p=moveBody([0,1.65,3],0,50,world);assert.ok(canStand(p[0],p[2],world));assert.ok(p[2]<4.8);const q=moveBody([-3,1.65,-3],0,-30,world);assert.ok(q[2]>-4.7);});
test('doorways are passable while adjacent walls are solid',()=>{assert.ok(canStand(0,-5,world));assert.ok(canStand(2,-14,world));assert.ok(canStand(5,0,world));assert.equal(canStand(-3,-5,world),false);assert.equal(canStand(-2,-14,world),false);assert.equal(canStand(5,3,world),false);});
test('routes around the off-center doorway actually arrive using collision movement',()=>{const target=world.rooms.find(r=>r.id==='back').waypoint,path=findPath(world.navigationStart.position,target,world);let p=[...world.navigationStart.position];for(const goal of path){let steps=0;while(Math.hypot(goal[0]-p[0],goal[2]-p[2])>.04&&steps++<3000){const dx=goal[0]-p[0],dz=goal[2]-p[2],d=Math.hypot(dx,dz),n=Math.min(.035,d);p=moveBody(p,dx/d*n,dz/d*n,world);}assert.ok(steps<3000,'movement stuck');}assert.ok(Math.hypot(target[0]-p[0],target[2]-p[2])<.06);});
test('each artwork has a reachable viewing position',()=>{for(const item of world.items){const p=item.position.map((v,i)=>v+item.normal[i]*2.5);p[1]=1.65;assert.ok(findPath(world.navigationStart.position,p,world)?.length,`ART_${item.index}`);}});
test('movement follows camera heading and diagonal speed stays normalized',()=>{assert.deepEqual(worldMovement(0,1,0,1),[0,-1]);const [dx,dz]=worldMovement(Math.PI/2,1,0,1);assert.ok(Math.abs(dx+1)<1e-10&&Math.abs(dz)<1e-10);assert.ok(Math.abs(Math.hypot(...worldMovement(.4,1,1,1))-1)<1e-10);});
