// Vince’s original albums: supplied files and Bandcamp listening copies.
export const tracks = [
  {
    "title": "This Is 30",
    "collection": "Happy Birthday To Me",
    "trackNumber": 1,
    "src": "audio/happy-birthday-to-me/01-this-is-30.mp3",
    "duration": 65.437,
    "color": "#a25235",
    "kind": "original",
    "cover": "audio/covers/happy-birthday-to-me.png"
  },
  {
    "title": "30 & Flirty",
    "collection": "Happy Birthday To Me",
    "trackNumber": 2,
    "src": "audio/happy-birthday-to-me/02-30-flirty.mp3",
    "duration": 87.301,
    "color": "#a25235",
    "kind": "original",
    "cover": "audio/covers/happy-birthday-to-me.png"
  },
  {
    "title": "30 Is The New 20",
    "collection": "Happy Birthday To Me",
    "trackNumber": 3,
    "src": "audio/happy-birthday-to-me/03-30-is-the-new-20.mp3",
    "duration": 81.763,
    "color": "#a25235",
    "kind": "original",
    "cover": "audio/covers/happy-birthday-to-me.png"
  },
  {
    "title": "Age Is Not A Destination. It’s A Journey.",
    "collection": "Happy Birthday To Me",
    "trackNumber": 4,
    "src": "audio/happy-birthday-to-me/04-age-is-not-a-destination-its-a-journey.mp3",
    "duration": 80.039,
    "color": "#a25235",
    "kind": "original",
    "cover": "audio/covers/happy-birthday-to-me.png"
  },
  {
    "title": "Dirty 30",
    "collection": "Happy Birthday To Me",
    "trackNumber": 5,
    "src": "audio/happy-birthday-to-me/05-dirty-30.mp3",
    "duration": 96.026,
    "color": "#a25235",
    "kind": "original",
    "cover": "audio/covers/happy-birthday-to-me.png"
  },
  {
    "title": "It Took 30 Years To Look This Good.",
    "collection": "Happy Birthday To Me",
    "trackNumber": 6,
    "src": "audio/happy-birthday-to-me/06-it-took-30-years-to-look-this-good.mp3",
    "duration": 75.337,
    "color": "#a25235",
    "kind": "original",
    "cover": "audio/covers/happy-birthday-to-me.png"
  },
  {
    "title": "Bonus Track: Magnolia's Drum Solo",
    "collection": "Happy Birthday To Me",
    "trackNumber": 7,
    "src": "audio/happy-birthday-to-me/07-bonus-track-magnolia-s-drum-solo.mp3",
    "duration": 104.777,
    "color": "#a25235",
    "kind": "original",
    "cover": "audio/covers/happy-birthday-to-me.png"
  },
  {
    "title": "1",
    "collection": "Fully Proper",
    "trackNumber": 1,
    "src": "audio/fully-proper/01-1.mp3",
    "duration": 66.9,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "2",
    "collection": "Fully Proper",
    "trackNumber": 2,
    "src": "audio/fully-proper/02-2.mp3",
    "duration": 98.116,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "3",
    "collection": "Fully Proper",
    "trackNumber": 3,
    "src": "audio/fully-proper/03-3.mp3",
    "duration": 43.128,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "4",
    "collection": "Fully Proper",
    "trackNumber": 4,
    "src": "audio/fully-proper/04-4.mp3",
    "duration": 60.97,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "5",
    "collection": "Fully Proper",
    "trackNumber": 5,
    "src": "audio/fully-proper/05-5.mp3",
    "duration": 115.957,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "6",
    "collection": "Fully Proper",
    "trackNumber": 6,
    "src": "audio/fully-proper/06-6.mp3",
    "duration": 117.447,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "7",
    "collection": "Fully Proper",
    "trackNumber": 7,
    "src": "audio/fully-proper/07-7.mp3",
    "duration": 104.072,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "8",
    "collection": "Fully Proper",
    "trackNumber": 8,
    "src": "audio/fully-proper/08-8.mp3",
    "duration": 142.707,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "9",
    "collection": "Fully Proper",
    "trackNumber": 9,
    "src": "audio/fully-proper/09-9.mp3",
    "duration": 80.274,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "10",
    "collection": "Fully Proper",
    "trackNumber": 10,
    "src": "audio/fully-proper/10-10.mp3",
    "duration": 99.605,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "11",
    "collection": "Fully Proper",
    "trackNumber": 11,
    "src": "audio/fully-proper/11-11.mp3",
    "duration": 111.491,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "12",
    "collection": "Fully Proper",
    "trackNumber": 12,
    "src": "audio/fully-proper/12-12.mp3",
    "duration": 86.23,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "13",
    "collection": "Fully Proper",
    "trackNumber": 13,
    "src": "audio/fully-proper/13-13.mp3",
    "duration": 34.22,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "14",
    "collection": "Fully Proper",
    "trackNumber": 14,
    "src": "audio/fully-proper/14-14.mp3",
    "duration": 32.731,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "15",
    "collection": "Fully Proper",
    "trackNumber": 15,
    "src": "audio/fully-proper/15-15.mp3",
    "duration": 55.014,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "16",
    "collection": "Fully Proper",
    "trackNumber": 16,
    "src": "audio/fully-proper/16-16.mp3",
    "duration": 98.116,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/fully-proper.png"
  },
  {
    "title": "Skipping Steps",
    "collection": "Right Here Ideas",
    "trackNumber": 1,
    "src": "audio/right-here-ideas/01-skipping-steps.mp3",
    "duration": 172.304,
    "color": "#56684a",
    "kind": "original",
    "cover": "audio/covers/right-here-ideas.png"
  },
  {
    "title": "Land Of Those People",
    "collection": "Right Here Ideas",
    "trackNumber": 2,
    "src": "audio/right-here-ideas/02-land-of-those-people.mp3",
    "duration": 240.771,
    "color": "#56684a",
    "kind": "original",
    "cover": "audio/covers/right-here-ideas.png"
  },
  {
    "title": "Day Old Watermelon",
    "collection": "Right Here Ideas",
    "trackNumber": 3,
    "src": "audio/right-here-ideas/03-day-old-watermelon.mp3",
    "duration": 96.627,
    "color": "#56684a",
    "kind": "original",
    "cover": "audio/covers/right-here-ideas.png"
  },
  {
    "title": "Wake Walking",
    "collection": "Right Here Ideas",
    "trackNumber": 4,
    "src": "audio/right-here-ideas/04-wake-walking.mp3",
    "duration": 108.513,
    "color": "#56684a",
    "kind": "original",
    "cover": "audio/covers/right-here-ideas.png"
  },
  {
    "title": "Too Times",
    "collection": "Right Here Ideas",
    "trackNumber": 5,
    "src": "audio/right-here-ideas/05-too-times.mp3",
    "duration": 129.332,
    "color": "#56684a",
    "kind": "original",
    "cover": "audio/covers/right-here-ideas.png"
  },
  {
    "title": "Taking Shadows",
    "collection": "Right Here Ideas",
    "trackNumber": 6,
    "src": "audio/right-here-ideas/06-taking-shadows.mp3",
    "duration": 108.513,
    "color": "#56684a",
    "kind": "original",
    "cover": "audio/covers/right-here-ideas.png"
  },
  {
    "title": "Nap",
    "collection": "Right Here Ideas",
    "trackNumber": 7,
    "src": "audio/right-here-ideas/07-nap.mp3",
    "duration": 87.719,
    "color": "#56684a",
    "kind": "original",
    "cover": "audio/covers/right-here-ideas.png"
  },
  {
    "title": "Protest Yourself",
    "collection": "Right Here Ideas",
    "trackNumber": 8,
    "src": "audio/right-here-ideas/08-protest-yourself.mp3",
    "duration": 200.647,
    "color": "#56684a",
    "kind": "original",
    "cover": "audio/covers/right-here-ideas.png"
  },
  {
    "title": "Stealing Phrases",
    "collection": "Right Here Ideas",
    "trackNumber": 9,
    "src": "audio/right-here-ideas/09-stealing-phrases.mp3",
    "duration": 121.887,
    "color": "#56684a",
    "kind": "original",
    "cover": "audio/covers/right-here-ideas.png"
  },
  {
    "title": "Magnolia",
    "collection": "Right Here Ideas",
    "trackNumber": 10,
    "src": "audio/right-here-ideas/10-magnolia.mp3",
    "duration": 115.853,
    "color": "#56684a",
    "kind": "original",
    "cover": "audio/covers/right-here-ideas.png"
  },
  {
    "title": "Pace",
    "collection": "Right Here Ideas",
    "trackNumber": 11,
    "src": "audio/right-here-ideas/11-pace.mp3",
    "duration": 108.408,
    "color": "#56684a",
    "kind": "original",
    "cover": "audio/covers/right-here-ideas.png"
  },
  {
    "title": "content AA",
    "collection": "Content",
    "trackNumber": 1,
    "src": "audio/content/01-content-aa.mp3",
    "duration": 170.789,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/content.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/content",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "content A",
    "collection": "Content",
    "trackNumber": 2,
    "src": "audio/content/02-content-a.mp3",
    "duration": 141.067,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/content.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/content",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "content B",
    "collection": "Content",
    "trackNumber": 3,
    "src": "audio/content/03-content-b.mp3",
    "duration": 124.72,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/content.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/content",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "content C",
    "collection": "Content",
    "trackNumber": 4,
    "src": "audio/content/04-content-c.mp3",
    "duration": 210.913,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/content.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/content",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "content D",
    "collection": "Content",
    "trackNumber": 5,
    "src": "audio/content/05-content-d.mp3",
    "duration": 84.5964,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/content.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/content",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "content E",
    "collection": "Content",
    "trackNumber": 6,
    "src": "audio/content/06-content-e.mp3",
    "duration": 108.374,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/content.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/content",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "content F",
    "collection": "Content",
    "trackNumber": 7,
    "src": "audio/content/07-content-f.mp3",
    "duration": 154.442,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/content.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/content",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "content S",
    "collection": "Content",
    "trackNumber": 8,
    "src": "audio/content/08-content-s.mp3",
    "duration": 262.926,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/content.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/content",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "content T",
    "collection": "Content",
    "trackNumber": 9,
    "src": "audio/content/09-content-t.mp3",
    "duration": 196.052,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/content.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/content",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Content U",
    "collection": "Content",
    "trackNumber": 10,
    "src": "audio/content/10-content-u.mp3",
    "duration": 178.219,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/content.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/content",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "one",
    "collection": "EL LOBO presents: Uber Thurman",
    "trackNumber": 1,
    "src": "audio/el-lobo-presents-uber-thurman/01-one.mp3",
    "duration": 417.478,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/el-lobo-presents-uber-thurman.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/el-lobo-presents-uber-thurman",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "two",
    "collection": "EL LOBO presents: Uber Thurman",
    "trackNumber": 2,
    "src": "audio/el-lobo-presents-uber-thurman/02-two.mp3",
    "duration": 123.234,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/el-lobo-presents-uber-thurman.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/el-lobo-presents-uber-thurman",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "three",
    "collection": "EL LOBO presents: Uber Thurman",
    "trackNumber": 3,
    "src": "audio/el-lobo-presents-uber-thurman/03-three.mp3",
    "duration": 210.913,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/el-lobo-presents-uber-thurman.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/el-lobo-presents-uber-thurman",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "four",
    "collection": "EL LOBO presents: Uber Thurman",
    "trackNumber": 4,
    "src": "audio/el-lobo-presents-uber-thurman/04-four.mp3",
    "duration": 75.6799,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/el-lobo-presents-uber-thurman.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/el-lobo-presents-uber-thurman",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "five",
    "collection": "EL LOBO presents: Uber Thurman",
    "trackNumber": 5,
    "src": "audio/el-lobo-presents-uber-thurman/05-five.mp3",
    "duration": 176.733,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/el-lobo-presents-uber-thurman.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/el-lobo-presents-uber-thurman",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "three one",
    "collection": "EL LOBO presents: Uber Thurman",
    "trackNumber": 6,
    "src": "audio/el-lobo-presents-uber-thurman/06-three-one.mp3",
    "duration": 126.207,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/el-lobo-presents-uber-thurman.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/el-lobo-presents-uber-thurman",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "four six",
    "collection": "EL LOBO presents: Uber Thurman",
    "trackNumber": 7,
    "src": "audio/el-lobo-presents-uber-thurman/07-four-six.mp3",
    "duration": 147.142,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/el-lobo-presents-uber-thurman.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/el-lobo-presents-uber-thurman",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "ABCs",
    "collection": "There It Is!",
    "trackNumber": 1,
    "src": "audio/there-it-is/01-abcs.mp3",
    "duration": 46.6466,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "More",
    "collection": "There It Is!",
    "trackNumber": 2,
    "src": "audio/there-it-is/02-more.mp3",
    "duration": 61.9619,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "What I mean",
    "collection": "There It Is!",
    "trackNumber": 3,
    "src": "audio/there-it-is/03-what-i-mean.mp3",
    "duration": 130.53,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Drug On",
    "collection": "There It Is!",
    "trackNumber": 4,
    "src": "audio/there-it-is/04-drug-on.mp3",
    "duration": 72.3389,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Told You",
    "collection": "There It Is!",
    "trackNumber": 5,
    "src": "audio/there-it-is/05-told-you.mp3",
    "duration": 44.3777,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "I Think",
    "collection": "There It Is!",
    "trackNumber": 6,
    "src": "audio/there-it-is/06-i-think.mp3",
    "duration": 119.286,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Screwdriver (White)",
    "collection": "There It Is!",
    "trackNumber": 7,
    "src": "audio/there-it-is/07-screwdriver-white.mp3",
    "duration": 109.176,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Simply Beautiful (Green)",
    "collection": "There It Is!",
    "trackNumber": 8,
    "src": "audio/there-it-is/08-simply-beautiful-green.mp3",
    "duration": 118.385,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Magnolia",
    "collection": "There It Is!",
    "trackNumber": 9,
    "src": "audio/there-it-is/09-magnolia.mp3",
    "duration": 111.712,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Noli Squad",
    "collection": "There It Is!",
    "trackNumber": 10,
    "src": "audio/there-it-is/10-noli-squad.mp3",
    "duration": 135.702,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Paramount",
    "collection": "There It Is!",
    "trackNumber": 11,
    "src": "audio/there-it-is/11-paramount.mp3",
    "duration": 98.732,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "MTP",
    "collection": "There It Is!",
    "trackNumber": 12,
    "src": "audio/there-it-is/12-mtp.mp3",
    "duration": 98.098,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Lil Stevie",
    "collection": "There It Is!",
    "trackNumber": 13,
    "src": "audio/there-it-is/13-lil-stevie.mp3",
    "duration": 74.8748,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/there-it-is.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/there-it-is",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "LEAVEBEFORE...",
    "collection": "EL'EP",
    "trackNumber": 1,
    "src": "audio/elep/01-leavebefore.mp3",
    "duration": 72.8148,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/elep.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/elep",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Q&A",
    "collection": "EL'EP",
    "trackNumber": 2,
    "src": "audio/elep/02-q-a.mp3",
    "duration": 96.586,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/elep.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/elep",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "MR.KNOWITALL",
    "collection": "EL'EP",
    "trackNumber": 3,
    "src": "audio/elep/03-mr-knowitall.mp3",
    "duration": 200.611,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/elep.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/elep",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "THE BRUISE",
    "collection": "EL'EP",
    "trackNumber": 4,
    "src": "audio/elep/04-the-bruise.mp3",
    "duration": 81.6242,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/elep.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/elep",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "ANOTHERPHOTO",
    "collection": "EL'EP",
    "trackNumber": 5,
    "src": "audio/elep/05-anotherphoto.mp3",
    "duration": 97.9711,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/elep.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/elep",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "For Jim",
    "collection": "EL LOBO proudly presents...'El Lobo'",
    "trackNumber": 1,
    "src": "audio/el-lobo-proudly-presents-el-lobo/01-for-jim.mp3",
    "duration": 151.486,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/el-lobo-proudly-presents-el-lobo.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/el-lobo-proudly-presents-el-lobo",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "El Lobo",
    "collection": "EL LOBO proudly presents...'El Lobo'",
    "trackNumber": 2,
    "src": "audio/el-lobo-proudly-presents-el-lobo/02-el-lobo.mp3",
    "duration": 71.2374,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/el-lobo-proudly-presents-el-lobo.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/el-lobo-proudly-presents-el-lobo",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "LA - 11:20:14, 6.:49 PM",
    "collection": "EL LOBO proudly presents...'El Lobo'",
    "trackNumber": 3,
    "src": "audio/el-lobo-proudly-presents-el-lobo/03-la-11-20-14-6-49-pm.mp3",
    "duration": 105.417,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/el-lobo-proudly-presents-el-lobo.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/el-lobo-proudly-presents-el-lobo",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Would You?",
    "collection": "EL LOBO proudly presents...'El Lobo'",
    "trackNumber": 4,
    "src": "audio/el-lobo-proudly-presents-el-lobo/04-would-you.mp3",
    "duration": 103.931,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/el-lobo-proudly-presents-el-lobo.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/el-lobo-proudly-presents-el-lobo",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Untitled Track (Introduction)",
    "collection": "GTGC",
    "trackNumber": 1,
    "src": "audio/gtgc/01-untitled-track-introduction.mp3",
    "duration": 45.8384,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/gtgc.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/gtgc",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Poison",
    "collection": "GTGC",
    "trackNumber": 2,
    "src": "audio/gtgc/02-poison.mp3",
    "duration": 69.8384,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/gtgc.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/gtgc",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Reading, PA",
    "collection": "GTGC",
    "trackNumber": 3,
    "src": "audio/gtgc/03-reading-pa.mp3",
    "duration": 104.748,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/gtgc.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/gtgc",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "November 2012",
    "collection": "GTGC",
    "trackNumber": 4,
    "src": "audio/gtgc/04-november-2012.mp3",
    "duration": 72.818,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/gtgc.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/gtgc",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Moanin'",
    "collection": "GTGC",
    "trackNumber": 5,
    "src": "audio/gtgc/05-moanin.mp3",
    "duration": 104.748,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/gtgc.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/gtgc",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "London Oil",
    "collection": "GTGC",
    "trackNumber": 6,
    "src": "audio/gtgc/06-london-oil.mp3",
    "duration": 69.8384,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/gtgc.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/gtgc",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Jenga",
    "collection": "GTGC",
    "trackNumber": 7,
    "src": "audio/gtgc/07-jenga.mp3",
    "duration": 75.7869,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/gtgc.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/gtgc",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "I've Got My Mind Set On You My Sweet Lord",
    "collection": "GTGC",
    "trackNumber": 8,
    "src": "audio/gtgc/08-i-ve-got-my-mind-set-on-you-my-sweet-lord.mp3",
    "duration": 52.3839,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/gtgc.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/gtgc",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Untitled Track #2",
    "collection": "GTGC",
    "trackNumber": 9,
    "src": "audio/gtgc/09-untitled-track-2.mp3",
    "duration": 50.5269,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/gtgc.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/gtgc",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "The Onion",
    "collection": "GTGC",
    "trackNumber": 10,
    "src": "audio/gtgc/10-the-onion.mp3",
    "duration": 43.0965,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/gtgc.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/gtgc",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "CMT",
    "collection": "GTGC",
    "trackNumber": 11,
    "src": "audio/gtgc/11-cmt.mp3",
    "duration": 17.4748,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/gtgc.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/gtgc",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "I'm Late",
    "collection": "Baby Steps",
    "trackNumber": 1,
    "src": "audio/baby-steps/01-i-m-late.mp3",
    "duration": 52.4309,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/baby-steps.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/baby-steps",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "El Lobo",
    "collection": "Baby Steps",
    "trackNumber": 2,
    "src": "audio/baby-steps/02-el-lobo.mp3",
    "duration": 52.4309,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/baby-steps.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/baby-steps",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Fudge Nugent",
    "collection": "Baby Steps",
    "trackNumber": 3,
    "src": "audio/baby-steps/03-fudge-nugent.mp3",
    "duration": 52.4309,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/baby-steps.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/baby-steps",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Gary On A Mission |>",
    "collection": "Baby Steps",
    "trackNumber": 4,
    "src": "audio/baby-steps/04-gary-on-a-mission.mp3",
    "duration": 87.3305,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/baby-steps.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/baby-steps",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Cracking Jack",
    "collection": "Baby Steps",
    "trackNumber": 5,
    "src": "audio/baby-steps/05-cracking-jack.mp3",
    "duration": 44.629,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/baby-steps.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/baby-steps",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "If You Want Me To Stay, Where Is The Money?",
    "collection": "Baby Steps",
    "trackNumber": 6,
    "src": "audio/baby-steps/06-if-you-want-me-to-stay-where-is-the-money.mp3",
    "duration": 192.052,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/baby-steps.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/baby-steps",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  },
  {
    "title": "Untitled",
    "collection": "Baby Steps",
    "trackNumber": 7,
    "src": "audio/baby-steps/07-untitled.mp3",
    "duration": 69.8691,
    "color": "#3157c8",
    "kind": "original",
    "cover": "audio/covers/baby-steps.jpg",
    "sourceAlbum": "https://diddypopdiddy.bandcamp.com/album/baby-steps",
    "sourceFormat": "Bandcamp MP3 128 kbps"
  }
];
